| No. | issue | title | labels | assignee | bot advice | created date |
| ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| 1 | [#21665](https://github.com/Azure/azure-sdk-for-python/issues/21665) | Typo in parameters | ['bug', 'Authorization', 'customer-reported', 'needs-team-attention', 'CXP Attention'] | ['MughundhanRaveendran-MSFT'] | new comment ! | 11-09  |
| 2 | [#21664](https://github.com/Azure/azure-sdk-for-python/issues/21664) | Documentation fix: Expe-<br/>cted type 'TokenCredent-<br/>ial', got 'UserPassCred-<br/>entials' instead | ['Docs', 'Network - DNS', 'customer-reported', 'needs-team-attention', 'CXP Attention'] | ['PramodValavala-MSFT'] | new comment ! | 11-09  |
| 3 | [#21642](https://github.com/Azure/azure-sdk-for-python/issues/21642) | 'MsiCredential' object -<br/>has no attribute 'signe-<br/>d_session' | ['customer-reported', 'Azure.Identity', 'Subscription', 'needs-team-attention'] | ['BigCat20196'] | new comment ! | 11-08  |
| 4 | [#21635](https://github.com/Azure/azure-sdk-for-python/issues/21635) | support to create/updat-<br/>e VpnSiteLinksOperation-<br/>s | ['feature-request', 'Service Attention', 'customer-reported', 'needs-team-attention', 'Network - Private Link'] | ['RAY-316'] |   | 11-07  |
| 5 | [#21467](https://github.com/Azure/azure-sdk-for-python/issues/21467) | B2B invitation endpoint-<br/> SDK | ['feature-request', 'Graph', 'Service Attention', 'customer-reported', 'needs-team-attention'] |   | new comment ! | 10-28  |
| 6 | [#21451](https://github.com/Azure/azure-sdk-for-python/issues/21451) | Azure function list pro-<br/>perties | ['question', 'Service Attention', 'customer-reported', 'Web Apps', 'needs-team-attention'] | ['BigCat20196'] | new comment ! | 10-27  |
| 7 | [#21450](https://github.com/Azure/azure-sdk-for-python/issues/21450) | Network resource provid-<br/>er API version is 8 ver-<br/>sions behind the latest-<br/> stable version | ['bug', 'Network', 'Service Attention'] |   | new comment ! | 10-27  |
| 8 | [#21449](https://github.com/Azure/azure-sdk-for-python/issues/21449) | Authorization Role Defi-<br/>nition Update The reque-<br/>sted resource does not -<br/>support http method 'PU-<br/>T':  | ['question', 'Authorization', 'Service Attention', 'customer-reported', 'needs-team-attention'] | ['SaurabhSharma-MSFT'] | new comment ! | 10-27  |
| 9 | [#21375](https://github.com/Azure/azure-sdk-for-python/issues/21375) | I can not update only o-<br/>ne key=value for the we-<br/>b app application setti-<br/>ng | ['feature-request', 'Service Attention', 'customer-reported', 'needs-team-attention'] | ['SaurabhSharma-MSFT'] | new comment ! | 10-22  |
| 10 | [#21301](https://github.com/Azure/azure-sdk-for-python/issues/21301) | [Python] reduce size fo-<br/>r `azure-mgmt-network` | [] | ['RAY-316'] |   | 10-18  |
| 11 | [#21252](https://github.com/Azure/azure-sdk-for-python/issues/21252) | from ._application_gate-<br/>ways_operations import -<br/>ApplicationGatewaysOper-<br/>ations  ValueError: sou-<br/>rce code string cannot -<br/>contain null bytes | ['bug', 'Network - Application Gateway', 'Service Attention', 'customer-reported', 'needs-team-attention'] | ['RAY-316'] | new comment ! | 10-14  |
| 12 | [#21008](https://github.com/Azure/azure-sdk-for-python/issues/21008) | KeyInfo for functions d-<br/>oesn't serialize correc-<br/>tly | ['bug', 'feature-request', 'Service Attention', 'customer-reported', 'Web Apps', 'needs-team-attention'] | ['BigCat20196'] |   | 10-01  |
| 13 | [#20907](https://github.com/Azure/azure-sdk-for-python/issues/20907) | Get the Azure VM IP inf-<br/>ormation | ['question', 'Compute', 'customer-reported', 'needs-team-attention'] | ['RAY-316'] |   | 09-28  |
| 14 | [#20804](https://github.com/Azure/azure-sdk-for-python/issues/20804) | Switching Tenant withou-<br/>t relogin | ['feature-request', 'Service Attention', 'customer-reported', 'ARM - Core', 'needs-team-attention'] |   | new comment ! | 09-23  |
| 15 | [#20802](https://github.com/Azure/azure-sdk-for-python/issues/20802) | Unable to authenticate -<br/>AzureStack using ADFS a-<br/>uthentication with User-<br/>PassCredentials | ['bug', 'Azure Stack', 'Service Attention', 'customer-reported', 'needs-team-attention'] |   | new comment ! | 09-23  |
| 16 | [#20679](https://github.com/Azure/azure-sdk-for-python/issues/20679) | Query ALL azure service-<br/>s available in EACH reg-<br/>ion by azure sdk for py-<br/>thon | ['question', 'customer-reported'] |   |   | 09-14  |
| 17 | [#20664](https://github.com/Azure/azure-sdk-for-python/issues/20664) | Azure data factory trig-<br/>ger creation using pyth-<br/>on SDK | ['question', 'Data Factory', 'Service Attention', 'customer-reported'] |   | new comment ! | 09-13  |
| 18 | [#20629](https://github.com/Azure/azure-sdk-for-python/issues/20629) | `top` parameter in Cons-<br/>umptionManagementClient-<br/> didn't return expectin-<br/>g list. | ['question', 'Service Attention', 'customer-reported', 'needs-team-attention', 'Consumption - UsageDetailsAndExport'] | ['BigCat20196'] | new comment ! | 09-09  |
| 19 | [#20372](https://github.com/Azure/azure-sdk-for-python/issues/20372) | Azure python api calls -<br/>gets stuck sometimes fo-<br/>r a long time | ['bug', 'Compute', 'Service Attention', 'customer-reported', 'needs-team-attention'] | ['jaylabell'] | new comment ! | 08-20  |
| 20 | [#20356](https://github.com/Azure/azure-sdk-for-python/issues/20356) | azure-mgmt-netapp: Oper-<br/>ation: 'Change Ownershi-<br/>p' is not permitted whe-<br/>n creating NFSv4.1 volu-<br/>me | ['bug', 'customer-reported', 'needs-team-attention'] | ['RAY-316'] |   | 08-19  |
| 21 | [#20288](https://github.com/Azure/azure-sdk-for-python/issues/20288) | The operation api.get i-<br/>n the module azure.mgmt-<br/>.apimanagement.operatio-<br/>ns doesn't return all t-<br/>he fields | ['bug', 'API Management', 'customer-reported', 'needs-team-attention'] | ['BigCat20196'] | new comment ! | 08-16  |
| 22 | [#20181](https://github.com/Azure/azure-sdk-for-python/issues/20181) | azure-mgmt-redis: LICEN-<br/>SE missing from PyPi | ['bug', 'customer-reported', 'needs-team-attention'] |   |   | 08-09  |
| 23 | [#20177](https://github.com/Azure/azure-sdk-for-python/issues/20177) | azure-mgmt-recoveryserv-<br/>ices: LICENSE missing f-<br/>rom PyPi | ['bug', 'customer-reported', 'needs-team-attention'] |   |   | 08-09  |
| 24 | [#20175](https://github.com/Azure/azure-sdk-for-python/issues/20175) | azure-mgmt-rdbms: LICEN-<br/>SE missing from PyPi | ['bug', 'customer-reported', 'needs-team-attention'] |   |   | 08-09  |
| 25 | [#20172](https://github.com/Azure/azure-sdk-for-python/issues/20172) | azure-mgmt-policyinsigh-<br/>ts: LICENSE missing fro-<br/>m PyPi | ['bug', 'customer-reported', 'needs-team-attention'] |   |   | 08-09  |
| 26 | [#20170](https://github.com/Azure/azure-sdk-for-python/issues/20170) | azure-mgmt-maps: LICENS-<br/>E missing from PyPi | ['bug', 'customer-reported'] |   |   | 08-09  |
| 27 | [#20168](https://github.com/Azure/azure-sdk-for-python/issues/20168) | azure-mgmt-loganalytics-<br/>: LICENSE missing in Py-<br/>Pi | ['bug', 'customer-reported', 'Monitor - LogAnalytics', 'needs-team-attention'] |   |   | 08-09  |
| 28 | [#20166](https://github.com/Azure/azure-sdk-for-python/issues/20166) | azure-mgmt-iotcentral: -<br/>LICENSE missing in PyPi-<br/> | ['bug', 'IoT', 'customer-reported', 'needs-team-attention'] |   |   | 08-09  |
| 29 | [#20163](https://github.com/Azure/azure-sdk-for-python/issues/20163) | azure-mgmt-datamigratio-<br/>n: LICENSE missing in P-<br/>yPi | ['bug', 'Data Migration', 'customer-reported', 'needs-team-attention'] |   |   | 08-09  |
| 30 | [#20161](https://github.com/Azure/azure-sdk-for-python/issues/20161) | azure-mgmt-databoxedge:-<br/> LICENSE missing in PyP-<br/>i | ['bug', 'customer-reported', 'needs-team-attention', 'DataBox Edge'] |   |   | 08-09  |
| 31 | [#20159](https://github.com/Azure/azure-sdk-for-python/issues/20159) | azure-mgmt-compute: LIC-<br/>ENSE missing in PyPi | ['bug', 'Compute', 'customer-reported', 'needs-team-attention'] |   |   | 08-09  |
| 32 | [#20155](https://github.com/Azure/azure-sdk-for-python/issues/20155) | azure-mgmt-batchai: LIC-<br/>ENSE file missing in py-<br/>pi | ['bug', 'BatchAI', 'customer-reported', 'needs-team-attention'] |   |   | 08-09  |
| 33 | [#20044](https://github.com/Azure/azure-sdk-for-python/issues/20044) | Follow-up: Is it possib-<br/>le to create a VM with -<br/>OS disk type different -<br/>than Premium SSD? | ['question', 'Compute - VM', 'Service Attention', 'customer-reported', 'needs-team-attention'] | ['RAY-316', 'oriwolman'] | new comment ! | 08-02  |
| 34 | [#19793](https://github.com/Azure/azure-sdk-for-python/issues/19793) | [azure-mgmt-sql] add su-<br/>pport for SQL replica | ['feature-request', 'SQL', 'Service Attention', 'customer-reported', 'needs-team-attention'] | ['RAY-316'] | new comment ! | 07-14  |
| 35 | [#19665](https://github.com/Azure/azure-sdk-for-python/issues/19665) | Error responses from ce-<br/>rtain operations do not-<br/> conform to ODataV4 | ['question', 'App Services', 'Service Attention', 'customer-reported'] | ['BigCat20196', 'RAY-316'] |   | 07-06  |
| 36 | [#19663](https://github.com/Azure/azure-sdk-for-python/issues/19663) | azure-mgmt-web 3.0.0: b-<br/>reaking changes without-<br/> migration information | ['question', 'App Services', 'Service Attention', 'customer-reported'] | ['RAY-316'] | new comment ! | 07-06  |
| 37 | [#19600](https://github.com/Azure/azure-sdk-for-python/issues/19600) | consumption SDK usage_d-<br/>etails.list does not fi-<br/>lter by date | ['bug', 'Service Attention', 'customer-reported', 'Consumption - UsageDetailsAndExport'] |   | new comment ! | 06-30  |
| 38 | [#19585](https://github.com/Azure/azure-sdk-for-python/issues/19585) | Aggregation strings are-<br/>n't listed | ['question', 'Monitor', 'Service Attention', 'customer-reported'] | ['RAY-316'] | new comment ! | 06-29  |
| 39 | [#19294](https://github.com/Azure/azure-sdk-for-python/issues/19294) | Which SDK to be used in-<br/> order to create a Expr-<br/>ess route circuit from -<br/>a Direct Port? | ['question', 'Network', 'Service Attention', 'customer-reported'] |   | new comment ! | 06-17  |
| 40 | [#19293](https://github.com/Azure/azure-sdk-for-python/issues/19293) | Add possibility to get -<br/>tags on subscription le-<br/>vel | ['feature-request', 'Service Attention', 'customer-reported', 'Subscription'] |   | new comment ! | 06-17  |
| 41 | [#19224](https://github.com/Azure/azure-sdk-for-python/issues/19224) | azure-mgmt-batch Pool c-<br/>reate incorrect API ver-<br/>sion | ['bug', 'Batch', 'Service Attention', 'customer-reported'] | ['RAY-316'] | new comment ! | 06-11  |
| 42 | [#19203](https://github.com/Azure/azure-sdk-for-python/issues/19203) | Cross references are br-<br/>oken | ['Docs', 'question', 'customer-reported', 'Subscription'] | ['RAY-316'] | new comment ! | 06-10  |
| 43 | [#19178](https://github.com/Azure/azure-sdk-for-python/issues/19178) | azure-mgmt-monitor thro-<br/>wing DeserializationErr-<br/>or when handling API er-<br/>ror | ['question', 'Monitor', 'customer-reported'] |   | new comment ! | 06-09  |
| 44 | [#19147](https://github.com/Azure/azure-sdk-for-python/issues/19147) | backup_protection_conta-<br/>iners.list got 400 erro-<br/>r | ['question', 'Recovery Services Backup', 'customer-reported'] | ['RAY-316'] | new comment ! | 06-08  |
| 45 | [#19009](https://github.com/Azure/azure-sdk-for-python/issues/19009) | azure-mgmt-resource doc-<br/>umentation is missing t-<br/>he module itself | ['bug', 'Docs', 'customer-reported'] | ['RAY-316'] |   | 05-31  |
| 46 | [#18957](https://github.com/Azure/azure-sdk-for-python/issues/18957) | azure-mgmt-costmanageme-<br/>nt CostManagementClient-<br/> does not handle api_ve-<br/>rsion | ['bug', 'Service Attention', 'Cost Management - Query'] |   | new comment ! | 05-26  |
| 47 | [#18937](https://github.com/Azure/azure-sdk-for-python/issues/18937) | Varying spelling of CBL-<br/>Mariner and CBL_MARINER-<br/> | ['question', 'Service Attention', 'Container Service'] |   | new comment ! | 05-25  |
| 48 | [#18928](https://github.com/Azure/azure-sdk-for-python/issues/18928) | Missing ImportSource (a-<br/>nd others) in azure.mgm-<br/>t.containerregistry.v20-<br/>19_04_01.models | ['question', 'Container Registry', 'customer-reported'] |   | new comment ! | 05-25  |
| 49 | [#18927](https://github.com/Azure/azure-sdk-for-python/issues/18927) | azure-mgmt-costmanageme-<br/>nt CostManagementClient-<br/> ignores nextLink for u-<br/>sage | ['bug', 'Service Attention', 'Cost Management - UsageDetailsAndExport'] | ['ShilpiGautam', 'olsaal-msft'] | new comment ! | 05-25  |
| 50 | [#18911](https://github.com/Azure/azure-sdk-for-python/issues/18911) | Network interface canno-<br/>t be modified by user C-<br/>ode: CannotModifyNicAtt-<br/>achedToPrivateEndpoint | ['bug', 'question', 'Network', 'Service Attention', 'customer-reported'] |   | new comment ! | 05-25  |
| 51 | [#18905](https://github.com/Azure/azure-sdk-for-python/issues/18905) | Bad body serialization -<br/>creating a Schedule Tri-<br/>gger in Data Factory | ['bug', 'Data Factory', 'Service Attention', 'customer-reported', 'needs-team-attention'] |   | new comment ! | 05-25  |
| 52 | [#18877](https://github.com/Azure/azure-sdk-for-python/issues/18877) | Python example invalid | ['bug', 'customer-reported'] |   |   | 05-24  |
| 53 | [#18873](https://github.com/Azure/azure-sdk-for-python/issues/18873) | The Python SDK passing -<br/>parameters to adf pipel-<br/>ine does not work | ['bug', 'Data Factory', 'customer-reported', 'needs-team-triage'] | ['00Kai0'] | new comment ! | 05-24  |
| 54 | [#18809](https://github.com/Azure/azure-sdk-for-python/issues/18809) | hardcoded API version i-<br/>n azure/mgmt/sql/operat-<br/>ions/_databases_operati-<br/>ons.py does not work fo-<br/>r all sovereign clouds | ['feature-request', 'SQL', 'Service Attention', 'customer-reported'] |   |   | 05-19  |
| 55 | [#18788](https://github.com/Azure/azure-sdk-for-python/issues/18788) | [API Management] Python-<br/> DSK not using all sche-<br/>ma data | ['bug', 'API Management', 'customer-reported'] |   |   | 05-18  |
| 56 | [#18433](https://github.com/Azure/azure-sdk-for-python/issues/18433) | [proposal not a bug] mi-<br/>ssing example how to pr-<br/>oceed with B2CTenantsOp-<br/>erations class | ['feature-request', 'customer-reported', 'needs-team-triage'] |   |   | 04-29  |
| 57 | [#18102](https://github.com/Azure/azure-sdk-for-python/issues/18102) | Content too old to follow | ['bug', 'Docs', 'question', 'MySQL', 'PostgreSQL', 'Service Attention', 'customer-reported'] |   | new comment ! | 04-16  |
| 58 | [#17801](https://github.com/Azure/azure-sdk-for-python/issues/17801) | Azure SDK is over 500MB-<br/> and growing on each re-<br/>lease. | ['question', 'Network', 'Service Attention', 'customer-reported'] | ['lmazuel'] | new comment ! | 04-05  |
| 59 | [#17764](https://github.com/Azure/azure-sdk-for-python/issues/17764) | Implement ExternalBeare-<br/>rTokenCredentialPolicy -<br/>in azure-mgmt-core  | ['Azure.Mgmt.Core'] | ['jiasli', '00Kai0'] | new comment ! | 04-02  |
| 60 | [#17439](https://github.com/Azure/azure-sdk-for-python/issues/17439) | Category of the sub-ass-<br/>essment | ['question', 'Security', 'Service Attention', 'customer-reported'] |   | new comment ! | 03-18  |
| 61 | [#16943](https://github.com/Azure/azure-sdk-for-python/issues/16943) | Feature To Append Tags -<br/>To A Resource | ['feature-request', 'customer-reported', 'needs-team-attention', 'needs-team-triage'] | ['xiangyan99', '00Kai0', 'RAY-316', 'jaylabell'] |   | 02-25  |
| 62 | [#15925](https://github.com/Azure/azure-sdk-for-python/issues/15925) | get public IP address a-<br/>t the same time when I -<br/>get VM information. | ['question', 'Compute', 'Compute - VM', 'customer-reported'] | ['00Kai0'] | new comment ! | 12-28  |
| 63 | [#15913](https://github.com/Azure/azure-sdk-for-python/issues/15913) | AzureFileVolume not unm-<br/>ounted on container del-<br/>ete done_callback  | ['question', 'customer-reported'] |   | new issue ! | 12-23  |
| 64 | [#15910](https://github.com/Azure/azure-sdk-for-python/issues/15910) | Creating ContainerInsta-<br/>nceManagementClient usi-<br/>ng client factory cause-<br/>s TypeError exception | ['question', 'customer-reported'] |   | new comment ! | 12-23  |
| 65 | [#15857](https://github.com/Azure/azure-sdk-for-python/issues/15857) | Subscription scope usag-<br/>e is not supported for -<br/>current api version | ['question', 'customer-reported'] |   | new issue ! | 12-17  |
| 66 | [#15732](https://github.com/Azure/azure-sdk-for-python/issues/15732) | Cannot Regenerate Stora-<br/>ge Account Access Key | ['Docs', 'question', 'customer-reported'] |   | new comment ! | 12-09  |
| 67 | [#15684](https://github.com/Azure/azure-sdk-for-python/issues/15684) | Get all 'Global adminis-<br/>trators' users in Azure-<br/> using python | ['question', 'Service Attention', 'customer-reported'] |   | new issue ! | 12-07  |
| 68 | [#15008](https://github.com/Azure/azure-sdk-for-python/issues/15008) | KeyVault library return-<br/>s less number of fields-<br/> when compared to Power-<br/>Shell command | ['question', 'KeyVault', 'customer-reported', 'needs-team-triage'] |   | new comment ! | 11-04  |
| 69 | [#13943](https://github.com/Azure/azure-sdk-for-python/issues/13943) | Error validating/creati-<br/>ng Storage Account | ['question', 'Service Attention', 'customer-reported'] |   |   | 09-22  |
